// Token allowlist + pool lookup shared types. Both JSON files are
// generated by scripts/build-allowlist.ts and scripts/discover-pools.ts.

export type TokenCategory = "stable" | "wrapped-native" | "blue-chip" | "long-tail";

export type StablePricing = {
  kind: "stable";
  usd: number; // hardcoded peg, usually 1.00
};

export type V3Pricing = {
  kind: "uniV3";
  pool: string; // lowercase pool contract address
  baseSymbol: string; // symbol of the other token in the pool (USDC, WETH, …)
  dex: string; // "uniswap-v3" | "pancake-v3" | "fusionx-v3" | …
};

export type V2Pricing = {
  kind: "uniV2";
  pool: string; // lowercase pair contract address
  baseSymbol: string;
  dex: string;
};

export type TokenSpec = {
  chainId: number;
  token: string; // lowercase contract address
  symbol: string;
  decimals: number;
  category: TokenCategory;
  marketCapRank: number; // CoinGecko global rank
  pricing: StablePricing | V3Pricing | V2Pricing;
};

// Output of discover-pools.ts: one row per pool we've identified.
// Used by the Swap/Sync handler to look up which token to update.
export type PoolSpec = {
  chainId: number;
  pool: string; // lowercase pool address
  dex: string;
  kind: "uniV3" | "uniV2";
  // The two tokens in the pool, normalised lowercase.
  token0: string;
  token1: string;
  decimals0: number;
  decimals1: number;
  // The token whose price this pool determines (the *other* one is the
  // anchor that we already price). Symbol included for logging.
  priceableToken: string;
  priceableSymbol: string;
  anchorToken: string;
  anchorSymbol: string;
};
