// AMM-based price discovery. Subscribes to Swap (V3) and Sync (V2) events
// on a curated list of pool addresses (see src/pricing/poolLookup.json,
// generated by scripts/discover-pools.ts).
//
// The handler is intentionally tiny: pool lookup → price math → upsert.
// No effects, no I/O. Stables (USDC, USDT, DAI, …) are not indexed —
// they're hardcoded $1.00 in src/pricing/tokenAllowlist.json and applied
// at the analytics layer.

import { indexer } from "generated";
import { v3PriceableInAnchor, v2PriceableInAnchor } from "./pricing/math.js";
import type { PoolSpec, TokenSpec } from "./pricing/types.js";

// `with { type: "json" }` works in Node 22+ ESM with the project's
// "module": "ESNext" + "moduleResolution": "bundler" tsconfig.
import poolLookupJson from "./pricing/poolLookup.json" with { type: "json" };
import tokenAllowlistJson from "./pricing/tokenAllowlist.json" with { type: "json" };
import headBlocksJson from "./pricing/headBlocks.json" with { type: "json" };

const POOLS: PoolSpec[] = poolLookupJson as PoolSpec[];
const ALLOWLIST: TokenSpec[] = tokenAllowlistJson as TokenSpec[];
// Per-chain head block at the time scripts/get-head-blocks.ts was run.
// Used as a `where: { block: { number: { _gte: HEAD } } }` filter on
// AMM Swap/Sync events so the indexer never backfills swap history —
// only forward pricing. Re-run get-head-blocks.ts before each restart.
const HEAD_BLOCKS: Record<string, number> = headBlocksJson;

// Per-chain pool address → spec. Built once at module load.
const POOL_BY_ADDR: Map<string, PoolSpec> = new Map();
for (const p of POOLS) {
  POOL_BY_ADDR.set(`${p.chainId}-${p.pool.toLowerCase()}`, p);
}

// (chainId, tokenAddress) → "stable" hardcoded USD value (e.g. USDC = 1.0).
// Lets us short-circuit the cascade when the anchor is a stable.
const STABLE_USD: Map<string, number> = new Map();
for (const t of ALLOWLIST) {
  if (t.pricing.kind === "stable") {
    STABLE_USD.set(`${t.chainId}-${t.token.toLowerCase()}`, t.pricing.usd);
  }
}

// Pull the latest USD price for the anchor token. Returns undefined if
// the anchor isn't priced yet — caller should skip this update and let
// the next Swap retry once the anchor has a price.
async function anchorPriceUSD(
  context: any,
  chainId: number,
  anchorToken: string,
): Promise<number | undefined> {
  const stable = STABLE_USD.get(`${chainId}-${anchorToken.toLowerCase()}`);
  if (stable !== undefined) return stable;
  const row = await context.TokenPrice.get(`${chainId}-${anchorToken.toLowerCase()}`);
  if (!row) return undefined;
  // BigDecimal comes through as a string-like; coerce.
  return Number(row.priceUSD);
}

// Common upsert path used by both V3 and V2 handlers.
async function writePrice(
  context: any,
  spec: PoolSpec,
  priceableInAnchor: number,
  block: { number: number; timestamp: number },
) {
  if (priceableInAnchor === 0 || !Number.isFinite(priceableInAnchor)) return;
  const anchorUSD = await anchorPriceUSD(context, spec.chainId, spec.anchorToken);
  if (anchorUSD === undefined) return; // anchor not yet priced; retry on next Swap
  const priceUSD = priceableInAnchor * anchorUSD;
  if (!Number.isFinite(priceUSD) || priceUSD <= 0) return;

  context.TokenPrice.set({
    id: `${spec.chainId}-${spec.priceableToken}`,
    chainId: spec.chainId,
    token: spec.priceableToken,
    priceUSD: priceUSD.toString(), // BigDecimal accepts string
    lastUpdatedBlock: block.number,
    lastUpdatedTimestamp: BigInt(block.timestamp),
    pricingPool: spec.pool,
    pricingDex: spec.dex,
  });
}

indexer.onEvent({
  contract: "UniswapV3Pool",
  event: "Swap",
  where: ({ chain }) => {
    const head = HEAD_BLOCKS[String(chain.id)];
    return head == null ? false : { block: { number: { _gte: head } } };
  },
}, async ({ event, context }) => {
  const spec = POOL_BY_ADDR.get(`${event.chainId}-${event.srcAddress.toLowerCase()}`);
  if (!spec || spec.kind !== "uniV3") return;
  const priceable = v3PriceableInAnchor(
    event.params.sqrtPriceX96,
    spec.token0,
    spec.token1,
    spec.decimals0,
    spec.decimals1,
    spec.priceableToken,
  );
  await writePrice(context, spec, priceable, event.block);
});

indexer.onEvent({
  contract: "UniswapV2Pair",
  event: "Sync",
  where: ({ chain }) => {
    const head = HEAD_BLOCKS[String(chain.id)];
    return head == null ? false : { block: { number: { _gte: head } } };
  },
}, async ({ event, context }) => {
  const spec = POOL_BY_ADDR.get(`${event.chainId}-${event.srcAddress.toLowerCase()}`);
  if (!spec || spec.kind !== "uniV2") return;
  const priceable = v2PriceableInAnchor(
    BigInt(event.params.reserve0),
    BigInt(event.params.reserve1),
    spec.token0,
    spec.token1,
    spec.decimals0,
    spec.decimals1,
    spec.priceableToken,
  );
  await writePrice(context, spec, priceable, event.block);
});
